on:
  push:
    branches:    
    - 'master'
name: Publish on Netlify
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm install -g reveal-md
    - run: cp slides/reveal.json .
    - run: reveal-md slides/index.md --static site
    - run: cp -r slides/images/slide-background site/images
    - uses: netlify/actions/cli@master
      with:
        args: deploy --dir=site --prod
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
